import type { Metadata } from "next";
import { Geist, Geist_Mono, Anton_SC } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import HeroCarousel from "@/components/HeroCarousel";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import Contact from "@/components/Contact";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const antonSC = Anton_SC({
  variable: "--font-anton-sc",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${antonSC.variable} ${antonSC.variable} antialiased bg-white`}
      >
        <Toaster />
        <div className="fixed top-0 left-0 z-50 w-full ">
          <Navbar />
        </div>
        <HeroCarousel />

        {children}
        <Footer />

      </body>
    </html>
  );
}
